// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BlockUserReducer from "../block_user_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateDisplayPinReducer from "../create_display_pin_reducer";
import CreateInviteTokenReducer from "../create_invite_token_reducer";
import CreateMessageTemplateReducer from "../create_message_template_reducer";
import CreatePasskeyChallengeReducer from "../create_passkey_challenge_reducer";
import CreateVenueReducer from "../create_venue_reducer";
import DeleteChannelReducer from "../delete_channel_reducer";
import DeleteDisplayDeviceReducer from "../delete_display_device_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import DeleteMessageTemplateReducer from "../delete_message_template_reducer";
import DeleteUserAccountReducer from "../delete_user_account_reducer";
import DeleteVenueReducer from "../delete_venue_reducer";
import DisplayConnectReducer from "../display_connect_reducer";
import ExtendSessionReducer from "../extend_session_reducer";
import JoinVenueReducer from "../join_venue_reducer";
import LeaveVenueReducer from "../leave_venue_reducer";
import LoginWithPasskeyReducer from "../login_with_passkey_reducer";
import PingReducer from "../ping_reducer";
import RegisterDisplayToVenueReducer from "../register_display_to_venue_reducer";
import RegisterNewUserWithPasskeyReducer from "../register_new_user_with_passkey_reducer";
import RegisterPasskeyReducer from "../register_passkey_reducer";
import RepeatMessageReducer from "../repeat_message_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetChannelRoleReducer from "../set_channel_role_reducer";
import SetVenueRoleReducer from "../set_venue_role_reducer";
import SkipMissedMessagesReducer from "../skip_missed_messages_reducer";
import UnblockUserReducer from "../unblock_user_reducer";
import UnpairDisplayReducer from "../unpair_display_reducer";
import UpdateChannelReducer from "../update_channel_reducer";
import UpdateDisplayNameReducer from "../update_display_name_reducer";
import UpdateMessageDeliveryStatusReducer from "../update_message_delivery_status_reducer";
import UpdateMessageTemplateReducer from "../update_message_template_reducer";
import UpdateUserNameReducer from "../update_user_name_reducer";
import UpdateVenueReducer from "../update_venue_reducer";

export type BlockUserParams = __Infer<typeof BlockUserReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateDisplayPinParams = __Infer<typeof CreateDisplayPinReducer>;
export type CreateInviteTokenParams = __Infer<typeof CreateInviteTokenReducer>;
export type CreateMessageTemplateParams = __Infer<typeof CreateMessageTemplateReducer>;
export type CreatePasskeyChallengeParams = __Infer<typeof CreatePasskeyChallengeReducer>;
export type CreateVenueParams = __Infer<typeof CreateVenueReducer>;
export type DeleteChannelParams = __Infer<typeof DeleteChannelReducer>;
export type DeleteDisplayDeviceParams = __Infer<typeof DeleteDisplayDeviceReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type DeleteMessageTemplateParams = __Infer<typeof DeleteMessageTemplateReducer>;
export type DeleteUserAccountParams = __Infer<typeof DeleteUserAccountReducer>;
export type DeleteVenueParams = __Infer<typeof DeleteVenueReducer>;
export type DisplayConnectParams = __Infer<typeof DisplayConnectReducer>;
export type ExtendSessionParams = __Infer<typeof ExtendSessionReducer>;
export type JoinVenueParams = __Infer<typeof JoinVenueReducer>;
export type LeaveVenueParams = __Infer<typeof LeaveVenueReducer>;
export type LoginWithPasskeyParams = __Infer<typeof LoginWithPasskeyReducer>;
export type PingParams = __Infer<typeof PingReducer>;
export type RegisterDisplayToVenueParams = __Infer<typeof RegisterDisplayToVenueReducer>;
export type RegisterNewUserWithPasskeyParams = __Infer<typeof RegisterNewUserWithPasskeyReducer>;
export type RegisterPasskeyParams = __Infer<typeof RegisterPasskeyReducer>;
export type RepeatMessageParams = __Infer<typeof RepeatMessageReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetChannelRoleParams = __Infer<typeof SetChannelRoleReducer>;
export type SetVenueRoleParams = __Infer<typeof SetVenueRoleReducer>;
export type SkipMissedMessagesParams = __Infer<typeof SkipMissedMessagesReducer>;
export type UnblockUserParams = __Infer<typeof UnblockUserReducer>;
export type UnpairDisplayParams = __Infer<typeof UnpairDisplayReducer>;
export type UpdateChannelParams = __Infer<typeof UpdateChannelReducer>;
export type UpdateDisplayNameParams = __Infer<typeof UpdateDisplayNameReducer>;
export type UpdateMessageDeliveryStatusParams = __Infer<typeof UpdateMessageDeliveryStatusReducer>;
export type UpdateMessageTemplateParams = __Infer<typeof UpdateMessageTemplateReducer>;
export type UpdateUserNameParams = __Infer<typeof UpdateUserNameReducer>;
export type UpdateVenueParams = __Infer<typeof UpdateVenueReducer>;

