// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DeliveryStatus,
} from "./types";


export default __t.row({
  statusId: __t.u64().primaryKey().name("status_id"),
  messageId: __t.u64().name("message_id"),
  displayId: __t.u64().name("display_id"),
  get status() {
    return DeliveryStatus;
  },
  updatedAt: __t.timestamp().name("updated_at"),
});
