// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import BlockUserReducer from "./block_user_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateDisplayPinReducer from "./create_display_pin_reducer";
import CreateInviteTokenReducer from "./create_invite_token_reducer";
import CreateMessageTemplateReducer from "./create_message_template_reducer";
import CreatePasskeyChallengeReducer from "./create_passkey_challenge_reducer";
import CreateVenueReducer from "./create_venue_reducer";
import DeleteChannelReducer from "./delete_channel_reducer";
import DeleteDisplayDeviceReducer from "./delete_display_device_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import DeleteMessageTemplateReducer from "./delete_message_template_reducer";
import DeleteUserAccountReducer from "./delete_user_account_reducer";
import DeleteVenueReducer from "./delete_venue_reducer";
import DisplayConnectReducer from "./display_connect_reducer";
import ExtendSessionReducer from "./extend_session_reducer";
import JoinVenueReducer from "./join_venue_reducer";
import LeaveVenueReducer from "./leave_venue_reducer";
import LoginWithPasskeyReducer from "./login_with_passkey_reducer";
import PingReducer from "./ping_reducer";
import RegisterDisplayToVenueReducer from "./register_display_to_venue_reducer";
import RegisterNewUserWithPasskeyReducer from "./register_new_user_with_passkey_reducer";
import RegisterPasskeyReducer from "./register_passkey_reducer";
import RepeatMessageReducer from "./repeat_message_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetChannelRoleReducer from "./set_channel_role_reducer";
import SetVenueRoleReducer from "./set_venue_role_reducer";
import SkipMissedMessagesReducer from "./skip_missed_messages_reducer";
import UnblockUserReducer from "./unblock_user_reducer";
import UnpairDisplayReducer from "./unpair_display_reducer";
import UpdateChannelReducer from "./update_channel_reducer";
import UpdateDisplayNameReducer from "./update_display_name_reducer";
import UpdateMessageDeliveryStatusReducer from "./update_message_delivery_status_reducer";
import UpdateMessageTemplateReducer from "./update_message_template_reducer";
import UpdateUserNameReducer from "./update_user_name_reducer";
import UpdateVenueReducer from "./update_venue_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ChannelRow from "./channel_table";
import ChannelMemberRoleRow from "./channel_member_role_table";
import ChannelMemberRoleViewRow from "./channel_member_role_view_table";
import ChannelViewRow from "./channel_view_table";
import DisplayDeviceRow from "./display_device_table";
import DisplayDeviceViewRow from "./display_device_view_table";
import DisplayPairingPinRow from "./display_pairing_pin_table";
import DisplayPairingPinViewRow from "./display_pairing_pin_view_table";
import MessageRow from "./message_table";
import MessageDeliveryStatusRow from "./message_delivery_status_table";
import MessageDeliveryStatusViewRow from "./message_delivery_status_view_table";
import MessageTemplateRow from "./message_template_table";
import MessageTemplateViewRow from "./message_template_view_table";
import MessageViewRow from "./message_view_table";
import NotificationFilterRow from "./notification_filter_table";
import NotificationFilterViewRow from "./notification_filter_view_table";
import PasskeyChallengeRow from "./passkey_challenge_table";
import PasskeyChallengeSelfViewRow from "./passkey_challenge_self_view_table";
import UserRow from "./user_table";
import UserAuthRow from "./user_auth_table";
import UserIdentityRow from "./user_identity_table";
import UserIdentitySelfViewRow from "./user_identity_self_view_table";
import UserViewRow from "./user_view_table";
import VenueRow from "./venue_table";
import VenueInviteTokenRow from "./venue_invite_token_table";
import VenueMemberRow from "./venue_member_table";
import VenueMemberViewRow from "./venue_member_view_table";
import VenueViewRow from "./venue_view_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  Channel: __table({
    name: 'channel',
    indexes: [
      { accessor: 'channelId', name: 'channel_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'channel_name', name: 'channel_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
      { accessor: 'channel_venue_id', name: 'channel_venue_id_idx_btree', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
      { name: 'channel_channel_id_key', constraint: 'unique', columns: ['channelId'] },
    ],
  }, ChannelRow),
  ChannelMemberRole: __table({
    name: 'channel_member_role',
    indexes: [
      { accessor: 'channel_member_role_channel_id', name: 'channel_member_role_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'channel_member_role_user_id', name: 'channel_member_role_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, ChannelMemberRoleRow),
  DisplayDevice: __table({
    name: 'display_device',
    indexes: [
      { accessor: 'displayId', name: 'display_device_display_id_idx_btree', algorithm: 'btree', columns: [
        'displayId',
      ] },
      { accessor: 'display_device_identity', name: 'display_device_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'display_device_uid', name: 'display_device_uid_idx_btree', algorithm: 'btree', columns: [
        'uid',
      ] },
      { accessor: 'display_device_venue_id', name: 'display_device_venue_id_idx_btree', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
      { name: 'display_device_display_id_key', constraint: 'unique', columns: ['displayId'] },
    ],
  }, DisplayDeviceRow),
  DisplayPairingPin: __table({
    name: 'display_pairing_pin',
    indexes: [
      { accessor: 'display_pairing_pin_identity', name: 'display_pairing_pin_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'pin', name: 'display_pairing_pin_pin_idx_btree', algorithm: 'btree', columns: [
        'pin',
      ] },
    ],
    constraints: [
      { name: 'display_pairing_pin_pin_key', constraint: 'unique', columns: ['pin'] },
    ],
  }, DisplayPairingPinRow),
  Message: __table({
    name: 'message',
    indexes: [
      { accessor: 'message_channel_id', name: 'message_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'messageId', name: 'message_message_id_idx_btree', algorithm: 'btree', columns: [
        'messageId',
      ] },
      { accessor: 'message_sender_id', name: 'message_sender_id_idx_btree', algorithm: 'btree', columns: [
        'senderId',
      ] },
    ],
    constraints: [
      { name: 'message_message_id_key', constraint: 'unique', columns: ['messageId'] },
    ],
  }, MessageRow),
  MessageDeliveryStatus: __table({
    name: 'message_delivery_status',
    indexes: [
      { accessor: 'delivery_status_display_id', name: 'message_delivery_status_display_id_idx_btree', algorithm: 'btree', columns: [
        'displayId',
      ] },
      { accessor: 'delivery_status_message_id', name: 'message_delivery_status_message_id_idx_btree', algorithm: 'btree', columns: [
        'messageId',
      ] },
      { accessor: 'statusId', name: 'message_delivery_status_status_id_idx_btree', algorithm: 'btree', columns: [
        'statusId',
      ] },
    ],
    constraints: [
      { name: 'message_delivery_status_status_id_key', constraint: 'unique', columns: ['statusId'] },
    ],
  }, MessageDeliveryStatusRow),
  MessageTemplate: __table({
    name: 'message_template',
    indexes: [
      { accessor: 'message_template_channel_id', name: 'message_template_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'templateId', name: 'message_template_template_id_idx_btree', algorithm: 'btree', columns: [
        'templateId',
      ] },
    ],
    constraints: [
      { name: 'message_template_template_id_key', constraint: 'unique', columns: ['templateId'] },
    ],
  }, MessageTemplateRow),
  NotificationFilter: __table({
    name: 'notification_filter',
    indexes: [
      { accessor: 'notification_filter_channel_id', name: 'notification_filter_channel_id_idx_btree', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { accessor: 'notification_filter_user_id', name: 'notification_filter_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, NotificationFilterRow),
  PasskeyChallenge: __table({
    name: 'passkey_challenge',
    indexes: [
      { accessor: 'identity', name: 'passkey_challenge_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'passkey_challenge_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PasskeyChallengeRow),
  User: __table({
    name: 'user',
    indexes: [
      { accessor: 'user_name', name: 'user_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
      { accessor: 'userId', name: 'user_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UserRow),
  UserAuth: __table({
    name: 'user_auth',
    indexes: [
      { accessor: 'user_auth_credential_id', name: 'user_auth_passkey_credential_id_idx_btree', algorithm: 'btree', columns: [
        'passkeyCredentialId',
      ] },
      { accessor: 'userId', name: 'user_auth_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_auth_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UserAuthRow),
  UserIdentity: __table({
    name: 'user_identity',
    indexes: [
      { accessor: 'identity', name: 'user_identity_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'user_identity_user_id', name: 'user_identity_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_identity_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserIdentityRow),
  Venue: __table({
    name: 'venue',
    indexes: [
      { accessor: 'venue_link', name: 'venue_link_idx_btree', algorithm: 'btree', columns: [
        'link',
      ] },
      { accessor: 'venue_name', name: 'venue_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
      { accessor: 'venueId', name: 'venue_venue_id_idx_btree', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
      { name: 'venue_venue_id_key', constraint: 'unique', columns: ['venueId'] },
    ],
  }, VenueRow),
  VenueInviteToken: __table({
    name: 'venue_invite_token',
    indexes: [
      { accessor: 'token', name: 'venue_invite_token_token_idx_btree', algorithm: 'btree', columns: [
        'token',
      ] },
      { accessor: 'venue_invite_token_venue_id', name: 'venue_invite_token_venue_id_idx_btree', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
      { name: 'venue_invite_token_token_key', constraint: 'unique', columns: ['token'] },
    ],
  }, VenueInviteTokenRow),
  VenueMember: __table({
    name: 'venue_member',
    indexes: [
      { accessor: 'venue_member_user_id', name: 'venue_member_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
      { accessor: 'venue_member_venue_id', name: 'venue_member_venue_id_idx_btree', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
    ],
  }, VenueMemberRow),
  ChannelMemberRoleView: __table({
    name: 'channel_member_role_view',
    indexes: [
    ],
    constraints: [
    ],
  }, ChannelMemberRoleViewRow),
  ChannelView: __table({
    name: 'channel_view',
    indexes: [
    ],
    constraints: [
    ],
  }, ChannelViewRow),
  DisplayDeviceView: __table({
    name: 'display_device_view',
    indexes: [
    ],
    constraints: [
    ],
  }, DisplayDeviceViewRow),
  DisplayPairingPinView: __table({
    name: 'display_pairing_pin_view',
    indexes: [
    ],
    constraints: [
    ],
  }, DisplayPairingPinViewRow),
  MessageDeliveryStatusView: __table({
    name: 'message_delivery_status_view',
    indexes: [
    ],
    constraints: [
    ],
  }, MessageDeliveryStatusViewRow),
  MessageTemplateView: __table({
    name: 'message_template_view',
    indexes: [
    ],
    constraints: [
    ],
  }, MessageTemplateViewRow),
  MessageView: __table({
    name: 'message_view',
    indexes: [
    ],
    constraints: [
    ],
  }, MessageViewRow),
  NotificationFilterView: __table({
    name: 'notification_filter_view',
    indexes: [
    ],
    constraints: [
    ],
  }, NotificationFilterViewRow),
  PasskeyChallengeSelfView: __table({
    name: 'passkey_challenge_self_view',
    indexes: [
    ],
    constraints: [
    ],
  }, PasskeyChallengeSelfViewRow),
  UserIdentitySelfView: __table({
    name: 'user_identity_self_view',
    indexes: [
    ],
    constraints: [
    ],
  }, UserIdentitySelfViewRow),
  UserView: __table({
    name: 'user_view',
    indexes: [
    ],
    constraints: [
    ],
  }, UserViewRow),
  VenueMemberView: __table({
    name: 'venue_member_view',
    indexes: [
    ],
    constraints: [
    ],
  }, VenueMemberViewRow),
  VenueView: __table({
    name: 'venue_view',
    indexes: [
    ],
    constraints: [
    ],
  }, VenueViewRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("block_user", BlockUserReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_display_pin", CreateDisplayPinReducer),
  __reducerSchema("create_invite_token", CreateInviteTokenReducer),
  __reducerSchema("create_message_template", CreateMessageTemplateReducer),
  __reducerSchema("create_passkey_challenge", CreatePasskeyChallengeReducer),
  __reducerSchema("create_venue", CreateVenueReducer),
  __reducerSchema("delete_channel", DeleteChannelReducer),
  __reducerSchema("delete_display_device", DeleteDisplayDeviceReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("delete_message_template", DeleteMessageTemplateReducer),
  __reducerSchema("delete_user_account", DeleteUserAccountReducer),
  __reducerSchema("delete_venue", DeleteVenueReducer),
  __reducerSchema("display_connect", DisplayConnectReducer),
  __reducerSchema("extend_session", ExtendSessionReducer),
  __reducerSchema("join_venue", JoinVenueReducer),
  __reducerSchema("leave_venue", LeaveVenueReducer),
  __reducerSchema("login_with_passkey", LoginWithPasskeyReducer),
  __reducerSchema("ping", PingReducer),
  __reducerSchema("register_display_to_venue", RegisterDisplayToVenueReducer),
  __reducerSchema("register_new_user_with_passkey", RegisterNewUserWithPasskeyReducer),
  __reducerSchema("register_passkey", RegisterPasskeyReducer),
  __reducerSchema("repeat_message", RepeatMessageReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_channel_role", SetChannelRoleReducer),
  __reducerSchema("set_venue_role", SetVenueRoleReducer),
  __reducerSchema("skip_missed_messages", SkipMissedMessagesReducer),
  __reducerSchema("unblock_user", UnblockUserReducer),
  __reducerSchema("unpair_display", UnpairDisplayReducer),
  __reducerSchema("update_channel", UpdateChannelReducer),
  __reducerSchema("update_display_name", UpdateDisplayNameReducer),
  __reducerSchema("update_message_delivery_status", UpdateMessageDeliveryStatusReducer),
  __reducerSchema("update_message_template", UpdateMessageTemplateReducer),
  __reducerSchema("update_user_name", UpdateUserNameReducer),
  __reducerSchema("update_venue", UpdateVenueReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

