// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Channel = __t.object("Channel", {
  channelId: __t.u64(),
  venueId: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  get minimumRoleToView() {
    return ChannelRole;
  },
  messageMaxAgeHours: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelMemberRole = __t.object("ChannelMemberRole", {
  channelId: __t.u64(),
  userId: __t.u64(),
  get role() {
    return ChannelRole;
  },
});
export type ChannelMemberRole = __Infer<typeof ChannelMemberRole>;

export const ChannelMemberRoleView = __t.object("ChannelMemberRoleView", {});
export type ChannelMemberRoleView = __Infer<typeof ChannelMemberRoleView>;

// The tagged union or sum type for the algebraic type `ChannelRole`.
export const ChannelRole = __t.enum("ChannelRole", {
  Owner: __t.string(),
  Admin: __t.string(),
  Moderator: __t.string(),
  Member: __t.string(),
});
export type ChannelRole = __Infer<typeof ChannelRole>;

export const ChannelView = __t.object("ChannelView", {});
export type ChannelView = __Infer<typeof ChannelView>;

// The tagged union or sum type for the algebraic type `DeliveryStatus`.
export const DeliveryStatus = __t.enum("DeliveryStatus", {
  Queued: __t.string(),
  InProgress: __t.string(),
  Shown: __t.string(),
  Skipped: __t.string(),
  Unavailable: __t.string(),
  Cancelled: __t.string(),
});
export type DeliveryStatus = __Infer<typeof DeliveryStatus>;

export const DisplayDevice = __t.object("DisplayDevice", {
  displayId: __t.u64(),
  uid: __t.string(),
  identity: __t.identity(),
  venueId: __t.u64(),
  name: __t.string(),
  registeredAt: __t.timestamp(),
  lastConnectedAt: __t.timestamp(),
});
export type DisplayDevice = __Infer<typeof DisplayDevice>;

export const DisplayDeviceView = __t.object("DisplayDeviceView", {});
export type DisplayDeviceView = __Infer<typeof DisplayDeviceView>;

export const DisplayPairingPin = __t.object("DisplayPairingPin", {
  pin: __t.string(),
  displayUid: __t.string(),
  identity: __t.identity(),
  expiresAt: __t.timestamp(),
});
export type DisplayPairingPin = __Infer<typeof DisplayPairingPin>;

export const DisplayPairingPinView = __t.object("DisplayPairingPinView", {});
export type DisplayPairingPinView = __Infer<typeof DisplayPairingPinView>;

export const Message = __t.object("Message", {
  messageId: __t.u64(),
  channelId: __t.u64(),
  senderId: __t.u64(),
  templateId: __t.option(__t.u64()),
  content: __t.string(),
  sentAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const MessageDeliveryStatus = __t.object("MessageDeliveryStatus", {
  statusId: __t.u64(),
  messageId: __t.u64(),
  displayId: __t.u64(),
  get status() {
    return DeliveryStatus;
  },
  updatedAt: __t.timestamp(),
});
export type MessageDeliveryStatus = __Infer<typeof MessageDeliveryStatus>;

export const MessageDeliveryStatusView = __t.object("MessageDeliveryStatusView", {});
export type MessageDeliveryStatusView = __Infer<typeof MessageDeliveryStatusView>;

export const MessageTemplate = __t.object("MessageTemplate", {
  templateId: __t.u64(),
  channelId: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  fieldsJson: __t.string(),
});
export type MessageTemplate = __Infer<typeof MessageTemplate>;

export const MessageTemplateView = __t.object("MessageTemplateView", {});
export type MessageTemplateView = __Infer<typeof MessageTemplateView>;

export const MessageView = __t.object("MessageView", {});
export type MessageView = __Infer<typeof MessageView>;

export const NotificationFilter = __t.object("NotificationFilter", {
  channelId: __t.u64(),
  userId: __t.u64(),
  get filterType() {
    return NotificationFilterType;
  },
  filterTextsJson: __t.string(),
});
export type NotificationFilter = __Infer<typeof NotificationFilter>;

// The tagged union or sum type for the algebraic type `NotificationFilterType`.
export const NotificationFilterType = __t.enum("NotificationFilterType", {
  EnableAll: __t.string(),
  DisableAll: __t.string(),
  FilteredText: __t.string(),
});
export type NotificationFilterType = __Infer<typeof NotificationFilterType>;

export const NotificationFilterView = __t.object("NotificationFilterView", {});
export type NotificationFilterView = __Infer<typeof NotificationFilterView>;

export const User = __t.object("User", {
  userId: __t.u64(),
  email: __t.option(__t.string()),
  passkeyCredentialId: __t.option(__t.string()),
  name: __t.string(),
  pushToken: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserAuth = __t.object("UserAuth", {
  userId: __t.u64(),
  passkeyCredentialId: __t.string(),
  passkeyPublicKey: __t.string(),
});
export type UserAuth = __Infer<typeof UserAuth>;

export const UserIdentity = __t.object("UserIdentity", {
  identity: __t.identity(),
  userId: __t.u64(),
  lastLogin: __t.timestamp(),
});
export type UserIdentity = __Infer<typeof UserIdentity>;

export const UserIdentityView = __t.object("UserIdentityView", {});
export type UserIdentityView = __Infer<typeof UserIdentityView>;

export const UserView = __t.object("UserView", {});
export type UserView = __Infer<typeof UserView>;

export const Venue = __t.object("Venue", {
  venueId: __t.u64(),
  name: __t.string(),
  link: __t.string(),
  createdAt: __t.timestamp(),
});
export type Venue = __Infer<typeof Venue>;

export const VenueInviteToken = __t.object("VenueInviteToken", {
  token: __t.string(),
  venueId: __t.u64(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type VenueInviteToken = __Infer<typeof VenueInviteToken>;

export const VenueInviteTokenView = __t.object("VenueInviteTokenView", {});
export type VenueInviteTokenView = __Infer<typeof VenueInviteTokenView>;

export const VenueMember = __t.object("VenueMember", {
  venueId: __t.u64(),
  userId: __t.u64(),
  joinDate: __t.timestamp(),
  lastSeen: __t.timestamp(),
  isBlocked: __t.bool(),
  get role() {
    return ChannelRole;
  },
});
export type VenueMember = __Infer<typeof VenueMember>;

export const VenueMemberView = __t.object("VenueMemberView", {});
export type VenueMemberView = __Infer<typeof VenueMemberView>;

export const VenueView = __t.object("VenueView", {});
export type VenueView = __Infer<typeof VenueView>;

