// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  messengerId: __t.u64().primaryKey().name("messenger_id"),
  uid: __t.string(),
  venueId: __t.u64().name("venue_id"),
  name: __t.string(),
  registeredAt: __t.timestamp().name("registered_at"),
  lastConnectedAt: __t.timestamp().name("last_connected_at"),
});
