// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BlockUserReducer from "../block_user_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateInviteTokenReducer from "../create_invite_token_reducer";
import CreateMessageTemplateReducer from "../create_message_template_reducer";
import CreateMessengerPinReducer from "../create_messenger_pin_reducer";
import CreateVenueReducer from "../create_venue_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import DeleteMessageTemplateReducer from "../delete_message_template_reducer";
import DeleteVenueReducer from "../delete_venue_reducer";
import JoinVenueReducer from "../join_venue_reducer";
import LeaveVenueReducer from "../leave_venue_reducer";
import LoginOrCreateUserReducer from "../login_or_create_user_reducer";
import LoginWithPasskeyReducer from "../login_with_passkey_reducer";
import MessengerConnectReducer from "../messenger_connect_reducer";
import RegisterMessengerToVenueReducer from "../register_messenger_to_venue_reducer";
import RegisterPasskeyReducer from "../register_passkey_reducer";
import RepeatMessageReducer from "../repeat_message_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetChannelRoleReducer from "../set_channel_role_reducer";
import SetVenueRoleReducer from "../set_venue_role_reducer";
import UnblockUserReducer from "../unblock_user_reducer";
import UpdateMessageDeliveryStatusReducer from "../update_message_delivery_status_reducer";
import UpdateMessageTemplateReducer from "../update_message_template_reducer";
import UpdatePushTokenReducer from "../update_push_token_reducer";
import UpdateVenueReducer from "../update_venue_reducer";

export type BlockUserParams = __Infer<typeof BlockUserReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateInviteTokenParams = __Infer<typeof CreateInviteTokenReducer>;
export type CreateMessageTemplateParams = __Infer<typeof CreateMessageTemplateReducer>;
export type CreateMessengerPinParams = __Infer<typeof CreateMessengerPinReducer>;
export type CreateVenueParams = __Infer<typeof CreateVenueReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type DeleteMessageTemplateParams = __Infer<typeof DeleteMessageTemplateReducer>;
export type DeleteVenueParams = __Infer<typeof DeleteVenueReducer>;
export type JoinVenueParams = __Infer<typeof JoinVenueReducer>;
export type LeaveVenueParams = __Infer<typeof LeaveVenueReducer>;
export type LoginOrCreateUserParams = __Infer<typeof LoginOrCreateUserReducer>;
export type LoginWithPasskeyParams = __Infer<typeof LoginWithPasskeyReducer>;
export type MessengerConnectParams = __Infer<typeof MessengerConnectReducer>;
export type RegisterMessengerToVenueParams = __Infer<typeof RegisterMessengerToVenueReducer>;
export type RegisterPasskeyParams = __Infer<typeof RegisterPasskeyReducer>;
export type RepeatMessageParams = __Infer<typeof RepeatMessageReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetChannelRoleParams = __Infer<typeof SetChannelRoleReducer>;
export type SetVenueRoleParams = __Infer<typeof SetVenueRoleReducer>;
export type UnblockUserParams = __Infer<typeof UnblockUserReducer>;
export type UpdateMessageDeliveryStatusParams = __Infer<typeof UpdateMessageDeliveryStatusReducer>;
export type UpdateMessageTemplateParams = __Infer<typeof UpdateMessageTemplateReducer>;
export type UpdatePushTokenParams = __Infer<typeof UpdatePushTokenReducer>;
export type UpdateVenueParams = __Infer<typeof UpdateVenueReducer>;

