// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.u64().primaryKey().name("user_id"),
  email: __t.option(__t.string()),
  passkeyCredentialId: __t.option(__t.string()).name("passkey_credential_id"),
  name: __t.string(),
  pushToken: __t.option(__t.string()).name("push_token"),
  createdAt: __t.timestamp().name("created_at"),
});
