// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import BlockUserReducer from "./block_user_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateInviteTokenReducer from "./create_invite_token_reducer";
import CreateMessageTemplateReducer from "./create_message_template_reducer";
import CreateMessengerPinReducer from "./create_messenger_pin_reducer";
import CreateVenueReducer from "./create_venue_reducer";
import DeleteChannelReducer from "./delete_channel_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import DeleteMessageTemplateReducer from "./delete_message_template_reducer";
import DeleteMessengerDeviceReducer from "./delete_messenger_device_reducer";
import DeleteUserAccountReducer from "./delete_user_account_reducer";
import DeleteVenueReducer from "./delete_venue_reducer";
import JoinVenueReducer from "./join_venue_reducer";
import LeaveVenueReducer from "./leave_venue_reducer";
import LoginOrCreateUserReducer from "./login_or_create_user_reducer";
import LoginWithPasskeyReducer from "./login_with_passkey_reducer";
import MessengerConnectReducer from "./messenger_connect_reducer";
import RegisterMessengerToVenueReducer from "./register_messenger_to_venue_reducer";
import RegisterPasskeyReducer from "./register_passkey_reducer";
import RepeatMessageReducer from "./repeat_message_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetChannelRoleReducer from "./set_channel_role_reducer";
import SetVenueRoleReducer from "./set_venue_role_reducer";
import UnblockUserReducer from "./unblock_user_reducer";
import UpdateChannelReducer from "./update_channel_reducer";
import UpdateMessageDeliveryStatusReducer from "./update_message_delivery_status_reducer";
import UpdateMessageTemplateReducer from "./update_message_template_reducer";
import UpdateMessengerNameReducer from "./update_messenger_name_reducer";
import UpdatePushTokenReducer from "./update_push_token_reducer";
import UpdateUserNameReducer from "./update_user_name_reducer";
import UpdateVenueReducer from "./update_venue_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ChannelRow from "./channel_table";
import ChannelMemberRoleRow from "./channel_member_role_table";
import MessageRow from "./message_table";
import MessageDeliveryStatusRow from "./message_delivery_status_table";
import MessageTemplateRow from "./message_template_table";
import MessengerDeviceRow from "./messenger_device_table";
import MessengerPairingPinRow from "./messenger_pairing_pin_table";
import NotificationFilterRow from "./notification_filter_table";
import UserRow from "./user_table";
import UserIdentityRow from "./user_identity_table";
import VenueRow from "./venue_table";
import VenueInviteTokenRow from "./venue_invite_token_table";
import VenueMemberRow from "./venue_member_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  Channel: __table({
    name: 'channel',
    indexes: [
      { name: 'channelId', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'channel_venue_id', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
      { name: 'channel_channel_id_key', constraint: 'unique', columns: ['channelId'] },
    ],
  }, ChannelRow),
  ChannelMemberRole: __table({
    name: 'channel_member_role',
    indexes: [
      { name: 'channel_member_role_channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'channel_member_role_user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, ChannelMemberRoleRow),
  Message: __table({
    name: 'message',
    indexes: [
      { name: 'message_channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'messageId', algorithm: 'btree', columns: [
        'messageId',
      ] },
    ],
    constraints: [
      { name: 'message_message_id_key', constraint: 'unique', columns: ['messageId'] },
    ],
  }, MessageRow),
  MessageDeliveryStatus: __table({
    name: 'message_delivery_status',
    indexes: [
      { name: 'delivery_status_message_id', algorithm: 'btree', columns: [
        'messageId',
      ] },
      { name: 'delivery_status_messenger_id', algorithm: 'btree', columns: [
        'messengerId',
      ] },
      { name: 'statusId', algorithm: 'btree', columns: [
        'statusId',
      ] },
    ],
    constraints: [
      { name: 'message_delivery_status_status_id_key', constraint: 'unique', columns: ['statusId'] },
    ],
  }, MessageDeliveryStatusRow),
  MessageTemplate: __table({
    name: 'message_template',
    indexes: [
      { name: 'message_template_channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'templateId', algorithm: 'btree', columns: [
        'templateId',
      ] },
    ],
    constraints: [
      { name: 'message_template_template_id_key', constraint: 'unique', columns: ['templateId'] },
    ],
  }, MessageTemplateRow),
  MessengerDevice: __table({
    name: 'messenger_device',
    indexes: [
      { name: 'messengerId', algorithm: 'btree', columns: [
        'messengerId',
      ] },
      { name: 'messenger_device_uid', algorithm: 'btree', columns: [
        'uid',
      ] },
      { name: 'messenger_device_venue_id', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
      { name: 'messenger_device_messenger_id_key', constraint: 'unique', columns: ['messengerId'] },
    ],
  }, MessengerDeviceRow),
  MessengerPairingPin: __table({
    name: 'messenger_pairing_pin',
    indexes: [
      { name: 'pin', algorithm: 'btree', columns: [
        'pin',
      ] },
    ],
    constraints: [
      { name: 'messenger_pairing_pin_pin_key', constraint: 'unique', columns: ['pin'] },
    ],
  }, MessengerPairingPinRow),
  NotificationFilter: __table({
    name: 'notification_filter',
    indexes: [
      { name: 'notification_filter_channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'notification_filter_user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
    ],
  }, NotificationFilterRow),
  User: __table({
    name: 'user',
    indexes: [
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UserRow),
  UserIdentity: __table({
    name: 'user_identity',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'user_identity_user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_identity_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserIdentityRow),
  Venue: __table({
    name: 'venue',
    indexes: [
      { name: 'venueId', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
      { name: 'venue_venue_id_key', constraint: 'unique', columns: ['venueId'] },
    ],
  }, VenueRow),
  VenueInviteToken: __table({
    name: 'venue_invite_token',
    indexes: [
      { name: 'token', algorithm: 'btree', columns: [
        'token',
      ] },
      { name: 'venue_invite_token_venue_id', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
      { name: 'venue_invite_token_token_key', constraint: 'unique', columns: ['token'] },
    ],
  }, VenueInviteTokenRow),
  VenueMember: __table({
    name: 'venue_member',
    indexes: [
      { name: 'venue_member_user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
      { name: 'venue_member_venue_id', algorithm: 'btree', columns: [
        'venueId',
      ] },
    ],
    constraints: [
    ],
  }, VenueMemberRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("block_user", BlockUserReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_invite_token", CreateInviteTokenReducer),
  __reducerSchema("create_message_template", CreateMessageTemplateReducer),
  __reducerSchema("create_messenger_pin", CreateMessengerPinReducer),
  __reducerSchema("create_venue", CreateVenueReducer),
  __reducerSchema("delete_channel", DeleteChannelReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("delete_message_template", DeleteMessageTemplateReducer),
  __reducerSchema("delete_messenger_device", DeleteMessengerDeviceReducer),
  __reducerSchema("delete_user_account", DeleteUserAccountReducer),
  __reducerSchema("delete_venue", DeleteVenueReducer),
  __reducerSchema("join_venue", JoinVenueReducer),
  __reducerSchema("leave_venue", LeaveVenueReducer),
  __reducerSchema("login_or_create_user", LoginOrCreateUserReducer),
  __reducerSchema("login_with_passkey", LoginWithPasskeyReducer),
  __reducerSchema("messenger_connect", MessengerConnectReducer),
  __reducerSchema("register_messenger_to_venue", RegisterMessengerToVenueReducer),
  __reducerSchema("register_passkey", RegisterPasskeyReducer),
  __reducerSchema("repeat_message", RepeatMessageReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_channel_role", SetChannelRoleReducer),
  __reducerSchema("set_venue_role", SetVenueRoleReducer),
  __reducerSchema("unblock_user", UnblockUserReducer),
  __reducerSchema("update_channel", UpdateChannelReducer),
  __reducerSchema("update_message_delivery_status", UpdateMessageDeliveryStatusReducer),
  __reducerSchema("update_message_template", UpdateMessageTemplateReducer),
  __reducerSchema("update_messenger_name", UpdateMessengerNameReducer),
  __reducerSchema("update_push_token", UpdatePushTokenReducer),
  __reducerSchema("update_user_name", UpdateUserNameReducer),
  __reducerSchema("update_venue", UpdateVenueReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

