// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  venueId: __t.u64().name("venue_id"),
  userId: __t.u64().name("user_id"),
  joinDate: __t.timestamp().name("join_date"),
  lastSeen: __t.timestamp().name("last_seen"),
  isBlocked: __t.bool().name("is_blocked"),
});
